### ISSUE TITLE
Bare hand fighting won't "equip"

### ISSUE THREAD

**Issue by Freso** [DaveDambonite/Loadout#1]
Playing a khajiit fist fighter, I wanted to make 1 my melee loadout slot. So I set him up with "Bare hands" or whatever the "weapon" is called and armour and other appareal. But when I try to switch to it, whatever else he's got equipped in his hands won't be unequipped/his bare fists won't be equipped.

I must admit I'm not entirely sure whether the hands are from SkyRe or due to playing khajiit, but they do appear equippable in my inventory, so they're favourited and was hotkeyed pre-Loadout. However, due to this, it's rather annoying to play with with this character.

**Comment by DaveDambonite** [comment]
Are you trying to say that a loadout with no weapon will not unequip a currently equipped weapon when activated? Or is there an item that does not work with Loadout?

I am aware of the fact that an item is not unequipped when it is worn in the hands. This is confusing because items worn 'on the body' are in face unequipped.

**Comment by DaveDambonite** [comment]
Loadout version 1.03 fixed this
